name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - setuptools==61.3.1
  - scipy
  - requests
  - datashader
  - holoviews
  - geoalchemy2
  - descartes
  - numpy
  - pandas
  - numba
  - geopandas
  - pygeos
  - matplotlib
  - flask
  - jupyterlab
  - pyarrow
  - sqlalchemy
  - dask
  - colorcet
  - pyproj
  - rasterio
  - xarray
  - bokeh
  - conda
  - geoviews
  - shapely
  - psycopg2
  - xlrd
  - h3-py
  - mapclassify
  - hdbscan
  - mercantile
  - contextily
  - moviepy
  - osmnx
  - rise
  - scikit-learn
  - pip:
    - osmium
    - wbdata
